services:
  db:
    image: postgres:15
    container_name: my-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: my-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: my-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # avoid mounting local node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    stdin_open: true     # for hot reload (optional)
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: