services:
  db-prod:
    image: postgres:18-alpine
    container_name: unemployed_db_prod
    environment:
      POSTGRES_DB: unemployed_prod
      POSTGRES_USER: unemployed_prod_user
      POSTGRES_PASSWORD: unemployed_prod_pass
    ports:
      - "5432:5432"
    volumes:
      - db_prod_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db-prod

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_prod_data: